/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/authscreen`; params?: Router.UnknownInputParams; } | { pathname: `/authscreen/login`; params?: Router.UnknownInputParams; } | { pathname: `/authscreen/signup`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/screen/createPost`; params?: Router.UnknownInputParams; } | { pathname: `/screen`; params?: Router.UnknownInputParams; } | { pathname: `/screen/details/detailsold`; params?: Router.UnknownInputParams; } | { pathname: `/screen/users/artistProfile`; params?: Router.UnknownInputParams; } | { pathname: `/screen/details/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/screen/users/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/authscreen`; params?: Router.UnknownOutputParams; } | { pathname: `/authscreen/login`; params?: Router.UnknownOutputParams; } | { pathname: `/authscreen/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/screen/createPost`; params?: Router.UnknownOutputParams; } | { pathname: `/screen`; params?: Router.UnknownOutputParams; } | { pathname: `/screen/details/detailsold`; params?: Router.UnknownOutputParams; } | { pathname: `/screen/users/artistProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/screen/details/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/screen/users/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/authscreen${`?${string}` | `#${string}` | ''}` | `/authscreen/login${`?${string}` | `#${string}` | ''}` | `/authscreen/signup${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/screen/createPost${`?${string}` | `#${string}` | ''}` | `/screen${`?${string}` | `#${string}` | ''}` | `/screen/details/detailsold${`?${string}` | `#${string}` | ''}` | `/screen/users/artistProfile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/authscreen`; params?: Router.UnknownInputParams; } | { pathname: `/authscreen/login`; params?: Router.UnknownInputParams; } | { pathname: `/authscreen/signup`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/screen/createPost`; params?: Router.UnknownInputParams; } | { pathname: `/screen`; params?: Router.UnknownInputParams; } | { pathname: `/screen/details/detailsold`; params?: Router.UnknownInputParams; } | { pathname: `/screen/users/artistProfile`; params?: Router.UnknownInputParams; } | `/screen/details/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/screen/users/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/screen/details/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/screen/users/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
